# Generated by Django 6.0.8 on 2026-08-26 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام نمایشی ربات (حداکثر ۱۲۰ کاراکتر)', max_length=120, verbose_name='نام استراتژی')),
                ('description', models.TextField(blank=True, default='', help_text='توضیحات اختیاری درباره تاکتیک و شیوه بازی ربات', verbose_name='توضیحات')),
                ('ai_prompt', models.TextField(blank=True, default='', help_text='متن فارسی استراتژی که برای ساخت این ربات به هوش مصنوعی داده شده است', verbose_name='متن پرامپت هوش مصنوعی')),
                ('strategy_data', models.JSONField(help_text='ساختار معتبر JSON استراتژی شامل قوانین (rules) و عملکرد پیش\u200cفرض (default_action)', verbose_name='داده\u200cهای JSON استراتژی')),
                ('is_public', models.BooleanField(default=False, help_text='اگر فعال باشد، یا اگر توسط ادمین ساخته شده باشد، برای تمام کاربران به عنوان حریف قابل انتخاب خواهد بود.', verbose_name='عمومی برای همه کاربران')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_strategies', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سازنده')),
            ],
            options={
                'verbose_name': 'استراتژی ذخیره\u200cشده',
                'verbose_name_plural': 'استراتژی\u200cهای ذخیره\u200cشده',
                'ordering': ['-updated_at'],
            },
        ),
    ]
