# Generated by Django 6.0.8 on 2026-08-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfigOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='نگاشت نام فیلد تنظیمات بازی به مقدار عددی.', verbose_name='مقادیر بازنویسی\u200cشده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایشگر')),
            ],
            options={
                'verbose_name': 'تنظیمات بازی',
                'verbose_name_plural': 'تنظیمات بازی',
            },
        ),
    ]
