# Generated by Django 6.0.8 on 2026-08-27 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameconfigoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='#2196F3', max_length=9, verbose_name='رنگ اصلی (خانه)')),
                ('away', models.CharField(default='#E6194B', max_length=9, verbose_name='رنگ دوم (میهمان)')),
                ('alternative', models.CharField(default='#FFB300', max_length=9, verbose_name='رنگ جایگزین')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kit', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رنگ تیم',
                'verbose_name_plural': 'رنگ\u200cهای تیم',
            },
        ),
    ]
