# Generated by Django 6.0.8 on 2026-08-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfigoverride',
            name='game_enabled',
            field=models.BooleanField(default=True, help_text='اگر غیرفعال شود، هیچ کاربری جز مدیران به بازی دسترسی نخواهد داشت.', verbose_name='بازی فعال است'),
        ),
    ]
