# Generated by Django 6.0.8 on 2026-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_usersession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfigoverride",
            name="session_limit",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="تعداد نشست\u200cهایی که هر کاربر عادی می\u200cتواند همزمان باز داشته باشد. با ورود جدید، قدیمی\u200cترین نشست\u200cهای اضافه بسته می\u200cشوند. مدیران مستثنا هستند.",
                verbose_name="حداکثر نشست همزمان",
            ),
        ),
    ]
