# Generated by Django 6.0.8 on 2026-08-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameconfigoverride_session_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfigoverride',
            name='strategy_strictness',
            field=models.PositiveSmallIntegerField(default=2, help_text='سطح پیش\u200cفرض سخت\u200cگیری هوش مصنوعی در تبدیل متن به استراتژی (از ۱ تا ۵).', verbose_name='سخت\u200cگیری پیش\u200cفرض استراتژی'),
        ),
    ]
