# Generated by Django 6.0.8 on 2026-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gameconfigoverride_strategy_strictness'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfigoverride',
            name='show_strictness_to_user',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، اسلایدر انتخاب سطح سخت\u200cگیری برای دانش\u200cآموزان نمایش داده می\u200cشود؛ در غیر این صورت مخفی شده و سطح پیش\u200cفرض ادمین اجباری اعمال می\u200cشود.', verbose_name='نمایش تنظیم سخت\u200cگیری به کاربر'),
        ),
    ]
