# Generated by Django 6.0.8 on 2026-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameconfigoverride_show_strictness_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfigoverride',
            name='strategy_limit',
            field=models.PositiveSmallIntegerField(default=4, help_text='حداکثر تعداد استراتژی\u200cهای ذخیره\u200cشده مجاز برای هر کاربر عادی (از ۱ تا ۱۰).', verbose_name='حداکثر استراتژی هر کاربر'),
        ),
    ]
