# Generated by Django 6.0.8 on 2026-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gameconfigoverride_strategy_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfigoverride',
            name='session_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='تعداد نشست\u200cهایی که هر کاربر عادی می\u200cتواند همزمان باز داشته باشد. با ورود جدید، قدیمی\u200cترین نشست\u200cهای اضافه بسته می\u200cشوند. مدیران مستثنا هستند.', verbose_name='حداکثر نشست همزمان'),
        ),
        migrations.AlterField(
            model_name='gameconfigoverride',
            name='show_strictness_to_user',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد، بخش انتخاب سطح سخت\u200cگیری برای دانش\u200cآموزان نمایش داده می\u200cشود؛ در غیر این صورت مخفی شده و سطح پیش\u200cفرض ادمین اجباری اعمال می\u200cشود.', verbose_name='امکان انتخاب سطح توسط کاربر'),
        ),
    ]
