# Generated by Django 6.0.8 on 2026-09-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_gameconfigoverride_session_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_label', models.CharField(blank=True, default='', max_length=64, verbose_name='نام نمایشی فرستنده')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('body', models.TextField(blank=True, default='', verbose_name='متن پیام')),
                ('to_everyone', models.BooleanField(default=False, help_text='اگر فعال باشد، فهرست کاربران نادیده گرفته می\u200cشود.', verbose_name='برای همه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال\u200cشده')], default='draft', max_length=8, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('users', models.ManyToManyField(blank=True, related_name='targeted_messages', to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان مشخص')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='game.message', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', '-id'], name='msg_status_recent'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', True), ('status', 'draft')), models.Q(('sent_at__isnull', False), ('status', 'sent')), _connector='OR'), name='msg_sent_at_matches_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-id'], name='notif_user_recent'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('read_at__isnull', True)), fields=['user'], name='notif_user_unread'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_notification_per_recipient'),
        ),
    ]
