# Generated by Django 6.0.8 on 2026-09-03 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_message_notification_message_msg_status_recent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('title', models.CharField(default='جام قهرمانی گیلبال', max_length=80, verbose_name='عنوان جدول')),
                ('size', models.PositiveSmallIntegerField(choices=[(2, '2'), (4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64')], default=16, verbose_name='تعداد تیم\u200cها')),
                ('teams', models.JSONField(blank=True, default=list, verbose_name='تیم\u200cهای دور اول')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='نتایج')),
                ('published', models.BooleanField(default=False, verbose_name='منتشرشده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایشگر')),
            ],
            options={
                'verbose_name': 'جدول حذفی',
                'verbose_name_plural': 'جدول حذفی',
            },
        ),
    ]
